                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                <Tr><td width=14>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
                        <!-- SIGNATURE HOMES -->
                        <?php   $prop_cat = 'Signature Homes';
                                $cat = 'signature_home';
                                $count_it = 1;
                        ?>
                    <td align=center width=148><?php echo "<a class=cat_header href=\"list.php?param=prop_cat&value=$prop_cat&search_cat=all_signature_home\">"; ?><?php echo "$prop_cat"; ?><?php echo "</a>"; ?></td>
                    <td width=14 align=center>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
                        <!-- SIGNATURE INNS -->
                        <?php   $prop_cat = 'Signature Hotels';
                                $cat = 'signature_hotel';
                                $count_it = 1;
                         ?>
                    <Td width=148 align=center><?php echo "<a class=cat_header href=\"list.php?param=prop_cat&value=$prop_cat&search_cat=all_signature_hotel\">"; ?><?php echo "$prop_cat"; ?><?php echo "</a>"; ?></td>
                    <td width=14 align=center>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
                        <!-- PREMIER HOMES -->
                        <?php   $prop_cat = 'Premier Homes';
                                $cat = 'premier_home';
                                $count_it = 1;
                        ?>
                    <Td width=148 align=center><?php echo "<a class=cat_header href=\"list.php?param=prop_cat&value=$prop_cat&search_cat=all_premier_home\">"; ?><?php echo "$prop_cat"; ?><?php echo "</a>"; ?></td>
                    <td width=14 align=center>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
                        <!-- PREMIER INNS -->
                        <?php   $prop_cat = 'Premier Hotels';
                                $cat = 'premier_hotel';
                                $count_it = 1;
                        ?>
                    <td width=148 align=center><?php echo "<a class=cat_header href=\"list.php?param=prop_cat&value=$prop_cat&search_cat=all_premier_hotel\">"; ?><?php echo "$prop_cat"; ?><?php echo "</a>"; ?></td>
                    <td width=14></td>
                </table>

