<? $get_prop_id = $_GET['prop_id']; ?>
                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                <Tr><td width=14>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
                    <td align=center width=148><a class=cat_header href="listing.php?prop_id=<?php echo "$get_prop_id"; ?>&cto=1">Contact The Owner</a></td>
                    <td width=14 align=center>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
					<td align=center width=148><a class=cat_header href="listing.php?prop_id=<?php echo "$get_prop_id"; ?>&fhh=1">48-Hour Hold</a></td>
                    <td width=14 align=center>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
					<td align=center width=148><a class=cat_header href="listing.php?prop_id=<?php echo "$get_prop_id"; ?>&bkt=1">Book It!</a></td>
                    <td width=14 align=center>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
                    <td align=center width=148><a class=cat_header href=""></a></td>
					<td width=14></td>
                </table>

