                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                <Tr><td width=1>
                        <table border=0 cellpadding=0 cellspacing=0 width=1>
                        <tr><td bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=12></td></tr>
                        </table>
                    </td>
                    <td align=center class=sub_nav_text>Solutions: Second Home Owner Edition</td>
                </table>

