
<!-- start premier inns -->
<table  cellpadding="5" cellspacing="1">
<tr>
<td bgcolor=#EFEFEF width="150"><p style="text-align: center;"><strong>
<span style="font-size: 1.4em;color: #2c5221;">
The River Street Inn</span><br />Truckee, California</strong></p>

<p><a href="http://www.kauaivacationhideaway.com/hideaway/index.html">
<img width="160" height="115" border="0" alt="Hideaway_bay_1" title="Hideaway_bay_1" src="/images/properties/river_street.gif" /></a>
</p>

<p>The River Street Inn is a great starting point for a picturesque Tahoe vacation.  <a href="http://www.kauaivacationhideaway.com/hideaway/index.html">More</a></p></td></tr></table>


<!-- end premier inns -->


