		<table border=0 cellpadding=0 cellspacing=0 width="100%">
		<tr><td width=1 bgcolor="#000000"><img src="img/clear.gif" width=1 height=1></td>
			<td>


                <table border=0 cellpadding=4 cellspacing=0 width="100%">
                <tr><td bgcolor="#ffffff" class=reg_copy >&nbsp;&nbsp;Search Using Google Maps</font></td></tr>
                </table>
                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                <tr><td height=1 bgcolor="#ffffff"><img src="img/clear.gif" width=1 height=1></td></tr>
                </table>
                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                <tr><Td bgcolor="#ffffff">
                    <table border=0 cellpadding=0 cellspacing=0 width="100%">
                    <tr><td><a href="map.php?map=na"><img src="img/map1.gif" border=0></a></td>
                        <td width=1><img src="img/clear.gif" width=1 height=1></td>
			<td><a href="map.php?map=ha"><img src="img/map2.gif" border=0></a></td>
			<td width=1><img src="img/clear.gif" width=1 height=1></td>
                        <td><a href="map.php?map=ca"><img src="img/map3.gif" border=0></a></td>
			<td width=1><img src="img/clear.gif" width=1 height=1></td>
                        <td><a href="map.php?map=ak"><img src="img/map4.gif" border=0></a></td>
                    </tr>
			<tr><td colspan=6 bgcolor="#ffffff"><img src="img/clear.gif" width=1 height=1></td></tr>
                    <tr bgcolor="#ffffff"><td class=reg_copy align=center>United States</td>
			<td width=1><img src="img/clear.gif" width=1 height=1></td>
                        <td class=reg_copy align=center>Hawaii</td>
			<td width=1><img src="img/clear.gif" width=1 height=1></td>
                        <td class=reg_copy align=center>Carribean</td>
			<td width=1><img src="img/clear.gif" width=1 height=1></td>
                        <td class=reg_copy align=center>Alaska</td>
                    </tr>
                    </table>

                </td></tr>
                </table>
			</td>
			<td width=1 bgcolor="#000000"><img src="img/clear.gif" width=1 height=1></td>
		</tR>
		</table>

