            <table border=0 cellpadding=0 cellspacing=0 width=250>
            <tr><td bgcolor="#f2eedf" width=1><img src="img/clear.gif" width=1 height=1></td>
                <td bgcolor="#f2eedf">
                <img src="img/clear.gif" width=1 height=5>
                <table border=0 cellpadding=0 cellspacing=0 widht="100%">
                <tr><td width=16><img src="img/clear.gif" width=18 height=1></td>
                    <td valign=top><span class=dark_left>Owners and Managers</span>

                        <br><img src="img/clear.gif" width=1 height=8><br>
                        <table border=0 cellpadding=0 cellspacing=0 width="100%">
                        <tr>
                            <td valign=top>
                                <table border=0 cellpadding=0 cellspacing=0>
                                <tr><Td valign=top><a href="list_a_property.php"><img src="img/left_scroll.gif" border=0 width=50 height=44></a></td>
                                    <td valign=top>
                                <table border=0 cellpadding=0 cellspacing=0 width="96%">
                                <tr><Td width=12><img src="img/clear.gif" width-12 height=1></td><td><a href="list_a_property.php" class=cat_header>List Your Property</a></td></tr>
                                <tr><td width=12></td><td class=small_text><table border=0 cellpadding=0 cellspacing=0><tr><td class=small_text>Click here, fill out a form and get your property listed on hvh.com!</td></tr></table></td></tr>
                                </table>
                                    </td>
                                </tr>
                                </table>
                            </td>
                        </tr>
                        <tr><td><img src="img/clear.gif" width=1 height=10></td></tr>
                        <tr>
                            <td valign=top>
                                 <table border=0 cellpadding=0 cellspacing=0>
                                <tr><Td valign=top><a href="solutions.php"><img src="img/left_house.gif" border=0 width=50 height=44></a></td>
                                    <td valign=top>
                                <table border=0 cellpadding=0 cellspacing=0 width="96%">
                                <tr><Td width=12><img src="img/clear.gif" width-12 height=1></td><td><a href="solutions.php" class=cat_header>Management Solutions</a></td></tr>
                                <tr><Td width=12><img src="img/clear.gif" width-12 height=1></td><td class=small_text><table border=0 cellpadding=0 cellspacing=0><tr><td class=small_text>2nd Home Owner, Hotel and Property Manager solutions.</td></tr></table></td></tr>
                                </table>
                                    </td>
                                </tr>
                                </table>
                            </td>
                        </tr>
                        </table>

                </td>
                </tr>
                 <tr><td colspan=2><img src="img/clear.gif" width=1 height=8></td></tr>
                </table>

                </td>
                <td width=1 bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=1></td>
            </tr>
            <tr>
                <td bgcolor="#ffffff" width=1><img src="img/clear.gif" width=1 height=1></td>
                <td colspan=2 bgcolor="#c0b7a9"><img src="img/clear.gif" width=1 height=2></td>
            </tr>
            <tr><td colspan=3 bgcolor="#ffffff"><img src="img/clear.gif" width=1 height=2></tr></tr>
            </table>
