<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr>
    <Td bgcolor="#ffffff" align=center class=right_header><img src="img/clear.gif" width=1 height=3><br><br><a href="solutions.php" class=cat_header><font color=black><b>Owners and Managers</b></font></a><br><img src="img/clear.gif" width=1 height=3></td></tr>
    <Td bgcolor="#ffffff" align=center class=search>
<table border=0 cellpadding=0 cellspacing=0 width="90%">
<tr><Td class=search align=center><br>
Maximize Bookings, Cultivate Customers, and run a better business.
<p>
<a href="solutions.php" class=cat_header><font color=black><u>HVH MANAGEMENT SOLUTIONS</u></font></a><p></td>
</tr>
</table>
      <img src="img/clear.gif" width=1 height=5><br>
        <a href="contact_us.php"><img src="img/scroll_white.gif" border=0 width=50 height=44 vspace=2></a>
        <br>
        <a href="contact_us.php"><font color="#333333">List Your Property</font color=white></a><Br>
        <img rc="img/clear.gif" width=1 height=5><br>
    </td>
</tr>
<tr>
    <Td align=center bgcolor="#ffffff" class=search>
        <img rc="img/clear.gif" width=1 height=5><br>
        <a href="solutions_second_home_owner.php"><img src="img/red_house_white.gif" border=0 vspace=2></a>
        <br>
        <a href="solutions_second_home_owner.php"><font color="#333333">2nd Home Owner</font></a>
        <br><img src="img/clear.gif" width=1 height=5><br>
    </td>
</tr>
<tr>
    <Td bgcolor="#ffffff" align=center class=search>
        <img rc="img/clear.gif" width=1 height=5><br>
        <a href="solutions_property_manager.php"><img src="img/lil_guy_white.gif" border=0 vspace=2></a>
        <br>
        <a href="solutions_property_manager.php"><font color="#333333">Property Manager</font></a>
        <br><img src="img/clear.gif" width=1 height=5><br>
    </td>
</tr>
<Tr>
    <Td bgcolor="#ffffff" align=center class=search>
        <img rc="img/clear.gif" width=1 height=5><br>
        <a href="solutions_hotels_inns.php"><img src="img/house_white.gif" border=0 width=50 height=44 vspace=2></a>
        <br>
        <a href="solutions_hotels_inns.php"><font color="#333333">Hotels and Huts</font></a>
	<Br><img src="img/clear.gif" width=1 height=5>
    </td>
</tr>
</table>
<table border=0 cellpadding=0 cellspacing=0 width="90%">
<tr><Td class=search align=center><br>
Nothing is simpler, more effective or more affordable. 
</td></tr>
</table>
