<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr>
    <Td bgcolor="#e2e2e1" align=center class=right_header><img src="img/clear.gif" width=1 height=3><br><a href="solutions.php"><font color=black>Owners and Managers</font></a><br><img src="img/clear.gif" width=1 height=3></td></tr>

<tr>
    <Td bgcolor="#496b97" align=center class=right_header>
        <img src="img/clear.gif" width=1 height=5><br>
        <a href="contact_us.php"><img src="img/scroll_white.gif" border=0 width=50 height=44 vspace=8></a>
        <br>
        <a href="contact_us.php" class=cat_header><font color=white>List Your Property</font color=white></a><Br>
        <img rc="img/clear.gif" width=1 height=5><br>
    </td>
</tr>
<tr>
    <Td bgcolor="#92cbee" align=center class=right_header><img src="img/clear.gif" width=1 height=3><Br><a href="solutions.php"><font color=black>Management Solutions</font></a><br><img src="img/clear.gif" width=1 height=3></td></tr>
<tr><td height=1 bgcolor="#496b97" colspan=2><img src="img/clear.gif" width=1 height=1></td></tr>
<tr>
    <Td align=center bgcolor="#d2eefe" class=right_header>
        <img rc="img/clear.gif" width=1 height=5><br>
        <a href="solutions_second_home_owner.php"><img src="img/red_house_white.gif" border=0 vspace=8></a>
        <br>
        <a href="solutions_second_home_owner.php" class=cat_header>2nd Home Owner</a>
        <br><img src="img/clear.gif" width=1 height=5><br>
    </td>
</tr>
<tr><td colspan=2 height=1 bgcolor="#496b97"><img src="img/clear.gif" width=1 height=1></td></tr>
<tr>
    <Td bgcolor="#d2eefe" align=center class=right_header>
        <img rc="img/clear.gif" width=1 height=5><br>
        <a href="solutions_property_manager.php"><img src="img/lil_guy_white.gif" border=0 vspace=8></a>
        <br>
        <a href="solutions_property_manager.php" class=cat_header>Property Manager</a>
        <br><img src="img/clear.gif" width=1 height=5><br>
    </td>
</tr>
<tr><td colspan=2 height=1 bgcolor="#496b97"><img src="img/clear.gif" width=1 height=1></td></tr>
<Tr>
    <Td bgcolor="#d2eefe" align=center class=right_header>
        <img rc="img/clear.gif" width=1 height=5><br>
        <a href="solutions_hotels_inns.php"><img src="img/house_white.gif" border=0 width=50 height=44 vspace=8></a>
        <br>
        <a href="solutions_hotels_inns.php" class=cat_header>Hotels and Huts</a>
	<Br><img src="img/clear.gif" width=1 height=5>
    </td>
</tr>
</table>
