<?php
   function getCountryCodeArray() {
   
      $countriesArray = array();

	  $countriesArray['US'] = 'UNITED STATES OF AMERICA';      
      // A
      $countriesArray['AL'] = 'ALBANIA';
      $countriesArray['DZ'] = 'ALGERIA';
      $countriesArray['AS'] = 'AMERICAN SAMOA';
      $countriesArray['AD'] = 'ANDORRA';
      $countriesArray['AI'] = 'ANGUILLA';
      $countriesArray['AG'] = 'ANTIGUA AND BARBUDA';
      $countriesArray['AR'] = 'ARGENTINA';
      $countriesArray['AM'] = 'ARMENIA';
      $countriesArray['AW'] = 'ARUBA';
      $countriesArray['AU'] = 'AUSTRALIA';
      $countriesArray['AT'] = 'AUSTRIA';
      $countriesArray['AZ'] = 'AZERBAIJAN';
      
      // B
      $countriesArray['BS'] = 'BAHAMAS';
      $countriesArray['BH'] = 'BAHRAIN';
      $countriesArray['BD'] = 'BANGLADESH';
      $countriesArray['BB'] = 'BARBADOS';
      $countriesArray['BY'] = 'BELARUS';
      $countriesArray['BE'] = 'BELGIUM';
      $countriesArray['BZ'] = 'BELIZE';
      $countriesArray['BJ'] = 'BENIN';
      $countriesArray['BM'] = 'BERMUDA';
      $countriesArray['BO'] = 'BOLIVIA';
      $countriesArray['BA'] = 'BOSNIA AND HERZEGOVINA';
      $countriesArray['BW'] = 'BOTSWANA';
      $countriesArray['BR'] = 'BRAZIL';
      $countriesArray['VG'] = 'BRITISH VIRGIN ISLANDS';
      $countriesArray['BN'] = 'BRUNEI';
      $countriesArray['BG'] = 'BULGARIA';
      $countriesArray['BF'] = 'BURKINA FASO';
      
      // C
      $countriesArray['KH'] = 'CAMBODIA';
      $countriesArray['CM'] = 'CAMEROON';
      $countriesArray['CA'] = 'CANADA';
      $countriesArray['CV'] = 'CAPE VERDE';
      $countriesArray['KY'] = 'CAYMAN ISLANDS';
      $countriesArray['CL'] = 'CHILE';
      $countriesArray['CN'] = 'CHINA';
      $countriesArray['CO'] = 'COLOMBIA';
      $countriesArray['CK'] = 'COOK ISLANDS';
      $countriesArray['HR'] = 'CROATIA';
      $countriesArray['CY'] = 'CYPRUS';
      $countriesArray['CZ'] = 'CZECH REPUBLIC';
      
      // D
      $countriesArray['DK'] = 'DENMARK';
      $countriesArray['DJ'] = 'DJIBOUTI';
      $countriesArray['DM'] = 'DOMINICA';
      $countriesArray['DO'] = 'DOMINICAN REPUBLIC';
      
      // E
      $countriesArray['TP'] = 'EAST TIMOR';
      $countriesArray['EG'] = 'EGYPT';
      $countriesArray['SV'] = 'EL SALVADOR';
      $countriesArray['EE'] = 'ESTONIA';
      
      // F
      $countriesArray['FJ'] = 'FIJI';
      $countriesArray['FI'] = 'FINLAND';
      $countriesArray['FR'] = 'FRANCE';
      $countriesArray['GF'] = 'FRENCH GUIANA';
      $countriesArray['PF'] = 'FRENCH POLYNESIA';
      
      // G
      $countriesArray['GA'] = 'GABON';
      $countriesArray['GE'] = 'GEORGIA';
      $countriesArray['DE'] = 'GERMANY';
      $countriesArray['GH'] = 'GHANA';
      $countriesArray['GI'] = 'GIBRALTAR';
      $countriesArray['GR'] = 'GREECE';
      $countriesArray['GD'] = 'GRENADA';
      $countriesArray['GP'] = 'GUADELOUPE';
      $countriesArray['GU'] = 'GUAM';
      $countriesArray['GT'] = 'GUATEMALA';
      $countriesArray['GN'] = 'GUINEA';
      $countriesArray['GY'] = 'GUYANA';
      
      // H
      $countriesArray['HT'] = 'HAITI';
      $countriesArray['HN'] = 'HONDURAS';
      $countriesArray['HK'] = 'HONG KONG';
      $countriesArray['HU'] = 'HUNGARY';
      
      // I
      $countriesArray['IS'] = 'ICELAND';
      $countriesArray['IN'] = 'INDIA';
      $countriesArray['ID'] = 'INDONESIA';
      $countriesArray['IE'] = 'IRELAND';
      $countriesArray['IL'] = 'ISRAEL';
      $countriesArray['IT'] = 'ITALY';
      $countriesArray['CI'] = 'IVORY COAST';
      
      // J
      $countriesArray['JM'] = 'JAMAICA';
      $countriesArray['JP'] = 'JAPAN';
      $countriesArray['JO'] = 'JORDAN';
      
      // K
      $countriesArray['KZ'] = 'KAZAKHSTAN';
      $countriesArray['KE'] = 'KENYA';
      $countriesArray['KW'] = 'KUWAIT';
      
      // L
      $countriesArray['LA'] = 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC';
      $countriesArray['LV'] = 'LATVIA';
      $countriesArray['LB'] = 'LEBANON';
      $countriesArray['LS'] = 'LESOTHO';
      $countriesArray['LT'] = 'LITHUANIA';
      $countriesArray['LU'] = 'LUXEMBOURG';
      
      // M
      $countriesArray['MO'] = 'MACAO';
      $countriesArray['MK'] = 'MACEDONIA';
      $countriesArray['MG'] = 'MADAGASCAR';
      $countriesArray['MY'] = 'MALAYSIA';
      $countriesArray['MV'] = 'MALDIVES';
      $countriesArray['ML'] = 'MALI';
      $countriesArray['MT'] = 'MALTA';
      $countriesArray['MH'] = 'MARSHALL ISLANDS';
      $countriesArray['MQ'] = 'MARTINIQUE';
      $countriesArray['MU'] = 'MAURITIUS';
      $countriesArray['MX'] = 'MEXICO';
      $countriesArray['FM'] = 'MICRONESIA, FEDERATED STATES OF';
      $countriesArray['MD'] = 'MOLDOVA';
      $countriesArray['MN'] = 'MONGOLIA';
      $countriesArray['MS'] = 'MONTSERRAT';
      $countriesArray['MA'] = 'MOROCCO';
      $countriesArray['MZ'] = 'MOZAMBIQUE';
      
      // N
      $countriesArray['NA'] = 'NAMIBIA';
      $countriesArray['NP'] = 'NEPAL';
      $countriesArray['NL'] = 'NETHERLANDS';
      $countriesArray['AN'] = 'NETHERLANDS ANTILLES';
      $countriesArray['NZ'] = 'NEW ZEALAND';
      $countriesArray['NI'] = 'NICARAGUA';
      $countriesArray['MP'] = 'NORTHERN MARIANA ISLANDS';
      $countriesArray['NO'] = 'NORWAY';
      
      // O
      $countriesArray['OM'] = 'OMAN';
      
      // P
      $countriesArray['PK'] = 'PAKISTAN';
      $countriesArray['PW'] = 'PALAU';
      $countriesArray['PS'] = 'PALESTINE';
      $countriesArray['PA'] = 'PANAMA';
      $countriesArray['PG'] = 'PAPUA NEW GUINEA';
      $countriesArray['PY'] = 'PARAGUAY';
      $countriesArray['PE'] = 'PERU';
      $countriesArray['PH'] = 'PHILIPPINES, REPUBLIC OF';
      $countriesArray['PL'] = 'POLAND';
      $countriesArray['PT'] = 'PORTUGAL';
      $countriesArray['PR'] = 'PUERTO RICO';
      
      // Q
      $countriesArray['QA'] = 'QATAR';
      
      // R
      $countriesArray['RO'] = 'ROMANIA';
      $countriesArray['RU'] = 'RUSSIAN FEDERATION';
      $countriesArray['RW'] = 'RWANDA';
      
      // S
      $countriesArray['KN'] = 'SAINT KITTS AND NEVIS';
      $countriesArray['LC'] = 'SAINT LUCIA';
      $countriesArray['VC'] = 'SAINT VINCENT AND THE GRENDINES';
      $countriesArray['WS'] = 'SAMOA';
      $countriesArray['SA'] = 'SAUDI ARABIA';
      $countriesArray['CS'] = 'SERBIA AND MONTENEGRO';
      $countriesArray['SC'] = 'SEYCHELLES';
      $countriesArray['SG'] = 'SINGAPORE';
      $countriesArray['SK'] = 'SLOVAKIA';
      $countriesArray['SI'] = 'SLOVENIA';
      $countriesArray['SB'] = 'SOLOMON ISLANDS';
      $countriesArray['ZA'] = 'SOUTH AFRICA';
      $countriesArray['KR'] = 'SOUTH KOREA';
      $countriesArray['ES'] = 'SPAIN';
      $countriesArray['LK'] = 'SRI LANKA';
      $countriesArray['SZ'] = 'SWAZILAND';
      $countriesArray['SE'] = 'SWEDEN';

      $countriesArray['CH'] = 'SWITZERLAND';
      
      // T
      $countriesArray['TW'] = 'TAIWAN';
      $countriesArray['TZ'] = 'TANZANIA, UNITED REPUBLIC OF';
      $countriesArray['TH'] = 'THAILAND';
      $countriesArray['TG'] = 'TOGO';
      $countriesArray['TO'] = 'TONGA';
      $countriesArray['TT'] = 'TRINIDAD AND TOBAGO';
      $countriesArray['TN'] = 'TUNISIA';
      $countriesArray['TR'] = 'TURKEY';
      $countriesArray['TM'] = 'TURKMENISTAN';
      $countriesArray['TC'] = 'TURKS AND CAICOS ISLANDS';
      
      // U
      $countriesArray['UG'] = 'UGANDA';
      $countriesArray['UA'] = 'UKRAINE';
      $countriesArray['AE'] = 'UNITED ARAB EMIRATES';
      $countriesArray['GB'] = 'UNITED KINGDOM';
      $countriesArray['UY'] = 'URUGUAY';
      $countriesArray['UZ'] = 'UZBEKISTAN';
      
      // V
      $countriesArray['VU'] = 'VANUATU';
      $countriesArray['VE'] = 'VENEZUELA';
      $countriesArray['VN'] = 'VIETNAM';
      $countriesArray['VI'] = 'VIRGIN ISLANDS, U.S.';
      
      // W, X, Y, Z
      $countriesArray['YE'] = 'YEMEN ARAB REPUBLIC';
      $countriesArray['ZM'] = 'ZAMBIA';
      
      return $countriesArray;
   }
     
?> 
