<!-- LEFT COLUMN -->
<td width=398 valign=top>
<!-- NOTHING ABOVE THIS LINE -->

<?php
// --- HOME PAGE -- LEFT COLUMN ELEMENTS --- //

include "elements/search.inc";	
include "elements/spacer.inc";
include "elements/map.inc";
include "elements/spacer.inc";
// include "elements/owners.inc";
// include "elements/spacer.inc";
// include "elements/solutions.inc"; 
// include "elements/spacer.inc";
include "elements/testimonials.inc";

?>
<!-- NOTHING BELOW THIS LINE -->                    	 
</td>

