<script language="JavaScript" type="text/javascript">
        AC_FL_RunContent(
                'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0',
                'width', '1000',
                'height', '150',
                'src', 'hvhbanner',
                'quality', 'high',
                'pluginspage', 'http://www.adobe.com/go/getflashplayer',
                'align', 'middle',
                'play', 'true',
                'loop', 'true',
                'scale', 'showall',
                'wmode', 'window',
                'devicefont', 'false',
                'id', 'hvhbanner',
                'bgcolor', '#ffffff',
                'name', 'hvhbanner',
                'menu', 'true',
                'allowFullScreen', 'false',
                'allowScriptAccess','sameDomain',
                'movie', 'hvhbanner',
                'salign', ''
                ); //end AC code
</script>
        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="1000" height="150" id="hvhbanner" align="middle">
        <param name="allowScriptAccess" value="sameDomain" />
        <param name="allowFullScreen" value="false" />
        <param name="movie" value="swf/hvhbanner.swf" />
        <param name="quality" value="high" /><param name="bgcolor" value="#ffffff" />
        <embed src="swf/hvhbanner.swf" loop='False' quality="high" bgcolor="#ffffff" width="1000" height="150" name="hvhbanner" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" />
        </object>
