<td valign=top class=content>
<!-- BEGIN CONTACT INFO - NOTHING ABOVE THIS LINE-->

<P>Hideaway Vacation Homes is a partnership of a group of people dedicated to providing a high level of service to our clients.  We share a common vision of providing a memorable and relaxing experience, and we bring different skills and interests to our work for you.</p>
<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Thomas Beebe</span></strong></span></p>

<p>Thomas has a B.S. in Landscape Architecture and has always been passionate about fixing and improving his surroundings. After 6 years of post-graduate traveling in search of the perfect place to live, he moved to Hawaii in 1998. </p>

<p>In 2000 he began managing capital improvements to the beautiful 3 acre Kauai property that have made <a href="http://www.kauaivacationhideaway.com/plumeria/" target=_blank>Plumeria Moon</a> and <a href="http://www.kauaivacationhideaway.com/" target=_blank>Hideaway Bay</a> so popular with guests ever since <a href="http://www.kauaivacationhideaway.com/" target=_blank>Kauai Vacation Hideaway</a> was created. </p>

<p>Thomas lives on the North Shore of Kauai with his wife Lyle, son Bodhi and daughter Talia.&nbsp; He manages the sales and marketing division of <a href="index.html">Hideaway Vacation Homes</a>.</p>		
<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Mike Testa</span></strong></span></p>
<p>Mike Testa is currently the Director of Strategic Accounts
at Salesforce.com.&nbsp; Mike and his team are focused on selling Customer
Relationship Management (CRM) applications to global companies like HP, FedEx,
Yahoo, Intel, eBay, Amazon, and National Semiconductor.&nbsp; Mike also serves
as the President and CEO of Hideaway Vacation Homes, <a href="index.html" title="http://www.hvh.com/">www.HVH.com</a>,
providing exclusive vacation rentals around the world.&nbsp; <br /><br />Finally, Mike serves on the Board of the <a href="http://www.absfoundation.org/programs.html" target=_blank>Arthur B. Schultz
Foundation</a>.&nbsp; As a Trustee, Mike is involved in coordinating funding for
Disabled Recreation, Global Understanding, Micro-Enterprise Lending, and
Environmental Conservation initiatives.&nbsp; Over the past 7 years, the ABS
Foundation has given over $3.5M dollars to worthy organizations around the
world.</p>				

<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Debbie ???</span></strong></span></p>
<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Tim ???</span></strong></span></p>
<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Fred ???</span></strong></span></p>
<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Jeff ???</span></strong></span></p>
<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Cindy Hultgren</span></strong></span></p>
<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Sy Testae</span></strong></span></p>
<p><span style="color: #666666;"><strong><span style="font-size: 1.4em;">Louis Balady</span></strong></span></p>

<p>Please call or email us anytime.&nbsp; We are committed to responding to you immediately and we look forward to speaking with you.</p>
<p><span style="font-weight: bold;">Thomas Beebe<br />888-858-6562<br /><a href="mailto:thomas@hvh.com">thomas@HVH.com</a><br /></span></p>
<p><span style="font-weight: bold;"></span></p>
<p><span style="font-weight: bold;">(If you are on the east coast, please consider that Hawaiian Standard Time is 5-6 hours behind you depending on daylight savings)<br /></span></p>

<!-- END CONTACT INFO - NOTHING BELOW THIS LINE -->
</td>
