<tr><Td class=entry_desc>*Card Type</td>
	<td class=entry_desc>
	<table border=0 cellpadding=0 cellspacing=0 width="100%">
	<tr><Td><select class="left" id="card_type">
			<option value="cardtype" selected="selected">Select a card type</option>
			<option value="visa">Visa</option>
			<option value="mastercard">MasterCard</option>
			<option value="amex">American Express</option>
		</select></td>
		<td><img src="img/ccpic.gif"></td>
	</tr>
	</table>
		
	</td>
</tr>
<tr><td class=entry_desc valign=top>*Card Number</td>
	<td class=entry_desc>

		<table border=0 cellpadding=0 cellspacing=0 width="100%">
		<Tr><td><input class=full maxlength="16" class="creditcard" type="text" value=""/></td>
		<td class=entry_desc width=1>&nbsp;&nbsp;*CVC&nbsp;</td><td width=1><input maxlength="4" type="text" id="cvc" value="" size=4/></td></tr>
		<Tr><Td class=entry_desc colspan=3><i>Numbers Only, No Spaces</i></td></tr>
		</table>

	

	</td>
</tr>
<tr><td class=entry_desc>*Expiration</td>
	<Td class=entry_desc><select id="month">
			<option value="january">01</option>
			<option value="february">02</option>
			<option value="march">03</option>

			<option value="april">04</option>
			<option value="may">05</option>
			<option value="june">06</option>
			<option value="july">07</option>
			<option value="august">08</option>
			<option value="september">09</option>

			<option value="october">10</option>
			<option value="november">11</option>
			<option value="december">12</option>
		</select>
		<select id="year">
			<option value="2008">2008</option>
			<option value="2009">2009</option>
			<option value="2010">2010</option>
			<option value="2011">2011</option>
			<option value="2012">2012</option>

			<option value="2013">2013</option>
			<option value="2014">2014</option>
			<option value="2015">2015</option>
			<option value="2016">2016</option>
			<option value="2017">2017</option>
			<option value="2018">2018</option>

			<option value="2019">2019</option>
			<option value="2020">2020</option>
			<option value="2021">2021</option>
			<option value="2022">2022</option>
			<option value="2023">2023</option>
			<option value="2024">2024</option>

			<option value="2025">2025</option>
			<option value="2026">2026</option>
		</select>
	</td>
</tr>
<tr><Td class=entry_desc>*Billing Address</td>
	<td><input class=full type="text" value="" name=billing_address/></td>
</tr>
<tr><Td class=entry_desc>*City</td>
	<Td>
	<table border=0 cellpadding=0 cellspacing=0 width="100%">	
	<tr><Td class=entry_desc><input class=full type="text" value="" name=billing_city/></td>
	<td class=entry_desc size=1>&nbsp;&nbsp;#Zip</td><td size=1><input class=full type="text" value="" name=billing_zip size= 10/></td></tr>
	</table>



	</td>
</tr>

