<td valign=top class=content>
<!-- BEGIN CONTACT INFO - NOTHING ABOVE THIS LINE-->

<p>Please call or email us anytime.&nbsp; We are committed to responding to you immediately and we look forward to speaking with you.</p>
<p><span style="font-weight: bold;">Thomas Beebe<br />888-858-6562<br /><a href="mailto:thomas@hvh.com">thomas@HVH.com</a><br /></span></p>
<p><span style="font-weight: bold;"></span></p>
<p><span style="font-weight: bold;">(If you are on the east coast, please consider that Hawaiian Standard Time is 5-6 hours behind you depending on daylight savings)<br /></span></p>
<br><br>
<!-- END CONTACT INFO - NOTHING BELOW THIS LINE -->
</td>
