<?php

	$features_array = array(

	"Fireplace__c",
	"Waterfront__c",
	"Kid_Friendly__c",
	"Views__c",
	"No_Smoking__c",
	"Ocean_View__c",
	"Mountain_View__c",
	"Pets_Allowed__c"

	);
	$features_hash = array(
	"Fireplace__c" => "Fireplace",
	"Waterfront__c" => "Waterfront",
	"Kid_Friendly__c" => "Kid Friendly",
	"Views__c" => "Views",
	"No_Smoking__c" => "No Smoking",
	"Ocean_View__c" => "Ocean View",
	"Mountain_View__c" => "Mountain View",
	"Pets_Allowed__c" => "Pets Allowed"
	);


	$outdoors_array = array(
	"Extremely_Private__c",
	"Patio_Lanai__c",
	"Large_Yard__c",
	"Tennis_Courts__c",
	"Outdoor_Shower__c",
	"Basketball_Hoop__c",
	"Hammock__c",
	"Volleyball_Court__c"		

	);

	$outdoors_hash = array(

	"Extremely_Private__c" => "Extremely Private",
	"Patio_Lanai__c" => "Patio/Lanai",
	"Large_Yard__c" => "Large Yard",
	"Tennis_Courts__c" => "Tennis Courts",
	"Outdoor_Shower__c" => "Outdoor Shower",
	"Basketball_Hoop__c" => "Basketball Hoop",
	"Hammock__c" => "Hammock",
	"Volleyball_Court__c" => "Volleyball Courts"		

	);

	// COMMUNICATIONS AND MULTIMEDIA OUTPUT //
	$comm_array = 
		array(	"Wireless_Internet__c",
				"High_Definition_TV_DVR__c",
				"Cable_Satellite_TV__c",
				"Unlimited_Domestic_Long_Distance__c",
				"Stereo_System__c", "CD_Player__c", 
				"Music_Library__c", 
				"VCR__c",
				"DVD_Player__c",
    			"Video_Library__c",
				"CD_Player__c",
				"Telephone__c",
				"Computer__c"
			
			);

	$comm_hash =
		array(
			"Wireless_Internet__c" => "Wireless Internet",
			"High_Definition_TV_DVR__c" => "High Definition TV/DVR",
			"Cable_Satellite_TV__c" => "Cable/Satellite TV",
			"Unlimited_Domestic_Long_Distance__c" => "Unlimited Domestic Long Distance",
    		"Stereo_System__c" => "Stereo System",
     		"CD_Player__c" => "CD Player",
    		"Music_Library__c" => "Music Library",
    		"VCR__c" => "VCR",
    		"DVD_Player__c" => "DVD Player",
    		"Video_Library__c" => "Video Library",
			"Telephone__c" => "Telephone",
			"Computer__c" => "Computer"
			);


	// BEDROOMS BATHROOMS SLEEPING OUTPUT //
	$bed_array = array(
			"Bath_Towels__c", 
			"Bed_Linens__c", 
			"Washer_Dryer__c",
			"Hair_Dryer__c",
			"Jets_in_Bathtub__c",
			"Crib__c"
	);
	
	$bed_hash = 
		array(
			"Bath_Towels__c" => "Bath Towels",
     		"Bed_Linens__c"  => "Bed Linens",
    		"Washer_Dryer__c" => "Washer/Dryer",
			"Hair_Dryer__c" => "Hair Dryer",
			"Jets_in_Bathtub__c" => "Jets in Bathtub",
			"Crib__c" => "Crib"
			);

	
	// KITCHEN OUTPUT //
	$kitchen_array = 
		array(
			"Refrigerator__c", "Dishwasher__c", "Oven__c",
    		"Microwave__c", "Cooking_Utensils__c", "Blender__c", "Ice_Maker__c"
			);
	$kitchen_hash = 
		array(
			"Refrigerator__c" => "Refrigerator",
     		"Dishwasher__c" => "Dishwasher",
    		"Oven__c" => "Oven",
    		"Microwave__c" => "Microwave",
			"Cooking_Utensils__c" => "Cooking Utensils",
			"Blender__c" => "Blender",
			"Ice_Maker__c" => "Ice Maker"
			);


	// SPECIAL AMENITIES OUTPUT //
    $amenities_array =
 	array(
		"Private_Hot_Tub__c", 
		"Swimming_Pool__c", 
		"Air_Conditioning__c",
		"Barbecue__c",
		"Washer_Dryer__c",
		"Garage_Parking__c",
		"Street_Parking__c"	
	);


    $amenities_hash =
	array(
	"Private_Hot_Tub__c" => "Private Hot Tub",
	"Swimming_Pool__c" => "Swimming Pool",
	"Air_Conditioning__c" => "Air Conditioning",
	"Barbecue__c" => "Barbecue",
	"Washer_Dryer__c" => "Washer/Dryer",
	"Garage_Parking__c" => "Garage Parking",
	"Street_Parking__c" => "Street Parking"
	);

?>
