                    <?php $limit = 3; ?>
                    <td width=550 valign=top>
                        <table border=0 cellpadding=0 cellspacing=0 width="100%">
                        <tr><td img src="img/clear.gif" width=1 height=15></td></tr>
                        </table>

                        
                        <!-- SIGNATURE HOMES -->
                        <?php $prop_cat = 'Signature Homes'; ?>
                        <table border=0 cellpadding=0 cellspacing=0 width="100%">
                        <tr class=list_sh>
                            <td class=list_sh><?php echo "$prop_cat"; ?></td>
                            <td class=list_sh><img src="img/clear.gif" width=1 height=1></td>
                            <td align=right class=list_sh><?php echo "<a href=\"list.php?param=prop_cat&value=$prop_cat\">"; ?>View All</a></td>
                        </tr>
                        <tr><td colspan=3 height=1><img src="img/clear.gif" width=1 height=1></td></tr>
                        <tr>
                            <td colspan=3>

                                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                                <tr>
                                <?php
                                include "content/home_row.inc";    
                                ?>    
                                </tr>
                                </table>

                            </td>
                        </tr>
                        </table>

                        <img src="img/clear.gif" width=1 height=2><br>

                        <!-- SIGNATURE INNS -->
                        <?php $prop_cat = 'Signature Inns'; ?>
                        <table border=0 cellpadding=0 cellspacing=0 width="100%">
                        <table border=0 cellpadding=0 cellspacing=0 width="100%">
                        <tr class=list_si>
                            <td class=list_si><?php echo "$prop_cat"; ?></td>
                            <td class=list_si><img src="img/clear.gif" width=1 height=1></td>
                            <td align=right class=list_si><?php echo "<a href=\"list.php?param=prop_cat&value=$prop_cat\">"; ?>View All</a></td>
                        </tr>
                        <tr><td colspan=3 height=1><img src="img/clear.gif" width=1 height=1></td></tr>
                        <tr>
                            <td colspan=3>

                                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                                <tr>
                                <?php
                                include "content/home_row.inc";
                                ?>    
                                </tr>   
                                </table>
    
                            </td>   
                        </tr>   
                        </table>

                        <img src="img/clear.gif" width=1 height=2><br>

                        <!-- PREMIER HOMES -->
                        <?php $prop_cat = 'Premier Homes'; ?>
                        <table border=0 cellpadding=0 cellspacing=0 width="100%">
                        <tr class=list_ph>
                            <td class=list_ph><?php echo "$prop_cat"; ?></td>
                            <td class=list_ph><img src="img/clear.gif" width=1 height=1></td>
                            <td align=right class=list_ph><?php echo "<a href=\"list.php?param=prop_cat&value=$prop_cat\">"; ?>View All</a></td>
                        </tr>
                        <tr><td colspan=3 height=1><img src="img/clear.gif" width=1 height=1></td></tr>
                        <tr>    
                            <td colspan=3>

                                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                                <tr>    
                                <?php
                                include "content/home_row.inc";
                                ?>
                                </tr>   
                                </table>
    
                            </td>   
                        </tr>   
                        </table>

                        <img src="img/clear.gif" width=1 height=2><br>

                        <!-- PREMIER INNS -->
                        <?php $prop_cat = 'Premier Inns'; ?>
                        <table border=0 cellpadding=0 cellspacing=0 width="100%">
                        <tr class=list_pi>
                            <td class=list_pi><?php echo "$prop_cat"; ?></td>
                            <td class=list_pi><img src="img/clear.gif" width=1 height=1></td>
                            <td align=right class=list_pi><?php echo "<a href=\"list.php?param=prop_cat&value=$prop_cat\">"; ?>View All</a></td>
                        </tr>
                        <tr><td colspan=3 height=1><img src="img/clear.gif" width=1 height=1></td></tr>
                        <tr>    
                            <td colspan=3>

                                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                                <tr>    
                                <?php
                                include "content/home_row.inc";
                                ?>
                                </tr>       
                                </table>
                            </td>       
                        </tr>       
                        </table>


                    </td>       
