                    <?php 
                        $prop_cat = $_GET['prop_cat'];
                    ?>
                    <td width="*%" valign=top align=center>
                        <table border=0 cellpadding=0 cellspacing=0 width="100%">
                        <tr><td img src="img/clear.gif" width=1 height=0></td></tr>
                        </table>
                        
                        <!-- DISPLAY THE SEARCH RESULTS -->
                                <?php
                                include "content/listing_detail.inc";    
                    
                                ?>  
                    <br /><br />           
                    </td>       
