<td valign=top class=content>
<!-- BEGIN PHILANTHROPY CONTENT - NOTHING ABOVE THIS LINE-->

<P>To honor our gratitude and respect for these beautiful destinations where we
offer vacation accommodations we have established philanthropy matching
projects in these areas. Guests are given the option to donate a
percentage of their rental expense to charitable organizations active
in local communities where they will be vacationing.</p>

<P>HVH is also partnered with the Arthur B. Schultz foundation <a href="http://www.absfoundation.org/programs.html">www.ABSfoundation.org</a>.</p>

<p>Please contact <a href="http://www.hvh.com/properties/contact.html">Thomas Beebe</a> to learn more about our philanthropy and matching contribution programs.</p><BR><BR>

<!-- END PHILANTHROPY  CONTENT -- NOTHING BELOW THIS LINE-->
</td>

