<td class=content valign=top>
<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td width=1><?php include "elements/solutions.inc"; ?></td>
    <td width=15><img src="img/clear.gif" width=15 height=1></td>
    <td><?php include "elements/solutions_right.inc"; ?></td>
</tr>
</table>

<br/>
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top width="60%">

<p>HVH provides everything a property manager needs to increase bookings and reduce expenses. We deliver and end-to-end, web based solution that manages the entire process from lead generation to recognized revenue.

<ul>
<li>Website/email Management <br>
<li>Sales & Marketing <br>
<li>Contact Management <br>
<li>Online Bookings & Reservations <br>
<li>Customer Database <br>
<li>Availability Calendar <br>
<li>Contracts and Rental Agreements <br>
<li>Maintenance Tracking <br>
<li>Fees and Commissions<Br>
<li>Financial Accounting<br>
<li>Occupancy Rate Reporting<br>
<li>Business Process Outsourcing<Br>
<li>Free listing on <a href="index.html">HVH.com</a>
</ul>

Pricing

<ul>
<li>Annual Subscription of $1995/yr includes 3 users and up to 50 properties.
<li>Integrated Financial Accounting Option is an addtional $1500/yr.
<li>Additional properties and users are available to for an additional fee. 
<!--Click here to become a partner: (Button for HVH.com/Partners) Purchase (Button to take someones credit card/paypal etc.) Product Spec Sheet (Button) Test Drive (www.appexchange.com) Usual Links along the bottom (hvh.com, contact us, love life, HVH Solutions)--></p><br><Br>
</ul>


</td>

<td valign=top align=right width="40%">

<a href="">Download the Product Spec Sheet</a><br/>
<a href="">Download the Company Overview</a><br/>
<a href="">See a demo of the 2nd Home Edition</a></br>

</td>
</tr>
</table>



<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
</td>
