<td class=content valign=top>
<! -- BEGIN SOLUTIONS CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td align=center>


<table border=0 cellpadding=0 cellspacing=0 width="100%">
<Tr>
<td width=75><img src="img/clear.gif" width=75 height=1></td>
<td width="33%" align=center>


	<table border=0 cellpadding=0 cellspacing=0>
	<Tr><Td align=center><a href="solutions_second_home_owner.php"><img src="img/sol_but_one.gif" border=0></a></td></tr>
	</table>
	<br>
	<table border=0 cellpadding=0 cellspacing=0 width=250>
	<tr><td colspan=3 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td></tr>
	<tr><td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=275></td>
		<td valign=top>
			<table border=0 cellpadding=6 cellspacing=10 width="100%">
			<tr><Td align=center><font size=4><b>Second Home</b></font></td></tr>
			<tr><td><font size=2>Tailored for the second home owner looking for a simple yet comprehensive system to manage every aspect of renting a property. A second home should be fun, not a hassle!</td></tr>
			
			<tr><td align=center><font size=2><b>$195/yr<br>1 Named User<br>1 Property</b></font></td></tr>
			</table>

		</td>
		<td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td>
	</tr>
	<tr><td colspan=3 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td></tr>	
	</table>


</td>


<td width="33%" align=center>

    <table border=0 cellpadding=0 cellspacing=0>
    <Tr><Td align=center><a href="solutions_property_manager.php"><img src="img/sol_but_two.gif" border=0 hspace=10></a></td></tr>
    </table>
    <br>
    <table border=0 cellpadding=0 cellspacing=0 width=250>
    <tr><td colspan=3 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td></tr>
    <tr><td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=275></td>
        <td valign=top>
            <table border=0 cellpadding=6 cellspacing=10 width="100%">
            <tr><Td align=center><font size=4><b>Property Management</b></font></td></tr>
            <tr><td><font size=2>This version allows property managers to track all properties, customers, bookings, owners, activities, and service providers through a single website. Avoid the bloated hardware and software.</td></tr>
            
            <tr><td align=center><font size=2><b>$595/yr<br>3 Named User<br>100 Properties</b></font></td></tr>
            </table>

        </td>
        <td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td>
    </tr>
    <tr><td colspan=3 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td></tr>
    </table>


</td>


<td width="33%" align=center valign=top>
    <table border=0 cellpadding=0 cellspacing=0>
    <Tr><Td align=center><a href="solutions_hotels_inns.php"><img src="img/sol_but_three.gif" border=0></a></td></tr>
    </table>
    <br>
    <table border=0 cellpadding=0 cellspacing=0 width=250>
    <tr><td colspan=3 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td></tr>
    <tr><td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=275></td>
        <td valign=top>
            <table border=0 cellpadding=6 cellspacing=10 width="100%">
            <tr><Td align=center><font size=4><b>Hotel</b></font></td></tr>
            <tr><td><font size=2>Drive business, manage the operation and maintain a satisfied repeat customer base. The Hotel Edition is quaint enough for a B&B and robust enough for hotel.</td></tr>
            
            <tr><td align=center><font size=2><b>$595/yr<br>3 Named User<br>100 Rooms</b></font></td></tr>
            </table>

        </td>
        <td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td>
    </tr>
    <tr><td colspan=3 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td></tr>
    </table>

</td>
<td width=75><img src="img/clear.gif" width=75 height=1></td>

</tr></table>



<Br><Br>

</td></tr>
</table>
<! -- END SOLUTIONS CONTENT - NOTHING BELOW THIS LINE -->
</td>
