<td class=content valign=top>
<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td width=1><?php include "elements/solutions.inc"; ?></td>
    <td width=15><img src="img/clear.gif" width=15 height=1></td>
    <td><?php include "elements/solutions_right.inc"; ?></td>
</tr>
</table>

<br/>
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top width="60%">

<p>
Whether you have a few rooms in a quaint Bed & Breakfast or a hundred rooms in a posh hotel, HVH Solutions offers end-to-end business applications that provide complete visibility into your business through real-time reporting and dashboards. Our web-based system delivers process efficiencies, higher revenues, and lower costs for much less than what you're paying today. <!--To download a total cost of ownership model, click here (webform).--> 
<br><Br>HVH has taken the ease of use of consumer sites like ebay, Amazon, Google, and Yahoo and created a business solution for the Vacation Rental Management Industry available through the browser. Our application is easy to use and intuitive to learn, yet comprehensive enough to run a large hotel. The solution offers everything a hotelier needs to track property maintenance, reservations, revenues, and expenses. Our system increases sales, improves internet reservation capture, automates bookings, and provides a permanent customer database. <!-->(Download detailed Product Spec Sheet Button)--> 
<br><Br>The HVH Hotel and B&B Edition also includes a complete list of functional capabilities:<br><br>


Annual Subscription of $1995/yr. includes 3 users and unlimited rooms. Integrated Financial Accounting Option is an addtional $1500/yr. Additional properties and users are available. <!--To download the US Price List, please click here (back to the webform). Purchase Here (Button to take someones credit card/paypal etc.) Download detailed Product Spec Sheet (Button) Take a Test Drive (www.appexchange.com) Usual Links along the bottom (hvh.com, contact us, love life, HVH Solutions)-->
</p><br><Br>





- Website/email Management <br>
- Sales & Marketing <br>
- Contact Management <br>
- Online Bookings & Reservations <br>
- Customer Database <br>
- Availability Calendar <br>
- Contracts and Rental Agreements <br>
- Maintenance Tracking <br>
- Fees and Commissions<Br>
- Financial Accounting<br>
- Occupancy Rate Reporting<br>
- Business Process Outsourcing<Br>
- Free listing on <a href="index.html">HVH.com!</a><br><Br>

Pricing - Annual Subscription of $1995/yr includes 3 users and up to 50 properties. Integrated Financial Accounting Option is an addtional $1500/yr. Additional properties and users are available to add to the subscription. <!--To download the US Price List, please click here (back to the webform).--> Our services can also be branded to give your customers a unique and personal experience by extending our service as part of a total property management solution for your clients. <!--Click here to become a partner: (Button for HVH.com/Partners) Purchase (Button to take someones credit card/paypal etc.) Product Spec Sheet (Button) Test Drive (www.appexchange.com) Usual Links along the bottom (hvh.com, contact us, love life, HVH Solutions)--></p><br><Br>


</td>

<td valign=top align=right width="40%">

<a href="">Download the Product Spec Sheet<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="">Download the Company Overview<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="">See a demo of the 2nd Home Edition<img src="img/pdf_ico_small.gif" hspace=6 border=0></a></br>

</td>
</tr>
</table>



<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
</td>
