<td class=content valign=top>
<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td width=1><?php include "elements/solutions.inc"; ?></td>
    <td width=15><img src="img/clear.gif" width=15 height=1></td>
</tr>
</table>

<br/>
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top width="60%">
<p>HVH Solutions 2nd Home Edition provides everything a homeowner needs to run a rental business.<br/><br/>
We deliver an end-to-end business solution including the following capabilities: 
<ul>
<li>Website/email Management
<li>Sales & Marketing
<li>Contact Management
<li>Online Booking
<li>Availability Calendar
<li>Contracts and Rental Agreements
<li>Maintenance Tracking
<li>Free listing on <a href="index.html">HVH.com</a>
</ul>
Pricing - Annual subscription of $595/yr for a single user with one property. <!--Additional users and properties are available and described in US Price List (Button: download here to the Price List) Button (purchase here) (link to credit card acceptance form) Button (download the product spec sheet) Take a test drive (www.appexchange.com)--></p><br><Br>
</td>

<td valign=top align=right width="40%">

<a href="">Download the Product Spec Sheet<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="">Download the Company Overview<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="">See a demo of the 2nd Home Edition<img src="img/pdf_ico_small.gif" hspace=6 border=0></a></br>

</td>
</tr>
</table>



<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
</td>
