    <script type="text/javascript" />
    //<![CDATA[

    if (GBrowserIsCompatible()) {
      var map = new GMap2(document.getElementById("Europe"));
      map.setCenter(new GLatLng(, ));
      map.setZoom(5);
      map.setMapType(G_NORMAL_MAP);
      var icon_palm = new GIcon();
      icon_palm.shadow = "http://hvh2.hvh.com/img/solopalm.png"
      icon_palm.shadowSize = new GSize(0, 0);
      icon_palm.iconAnchor = new GPoint(0, 0);
      icon_palm.infoWindowAnchor = new GPoint(0, 0);
      icon_palm.image = "http://hvh2.hvh.com/img/solopalm.png";

    }

    //]]>
    </script>