				<?php include "template/column_spacer.inc"; ?>
                </tr>
                <tr><td colspan=6 height=5><img src="img/clear.gif" width=1 height=5></td></tr>
                <!-- PHILANTHROPY BANNER-->
                <tr><td colspan=6 align=center>
					<table border=0 cellpadding=0 cellspacing=0>
					<tr><td colspan=3><a href="philanthropy.php"><img src="img/phil_top.gif" border=0></a></td></tr>
					<tr><td><a href="philanthropy.php"><img src="img/phil_left.gif" border=0></a></td>
						<td><a href="http://www.absfoundation.org" target=_blank><img src="img/phil_middle.gif" border=0></a></td>
						<td><a href="philanthropy.php"><img src="img/phil_right.gif" border=0></a></td>
					</tr>
					<tr><td colspan=3><a href="philanthropy.php"><img src="img/phil_bottom.gif" border=0></a></td></tr>
					</table>
				</a></td></tr>
                </table>

            </td></tr>

            <!-- MOUNTAINS BANNER -->
            <tr><Td colspan=6><img src="img/mountains.gif" border=0 width=998 height=147></td></tr>
            </table>
                    
        </td>
        <td bgcolor=black width=1><img src="img/clear.gif" width=1 height=1"></td>
    </tr>       
    <tr><td bgcolor=black colspan=3 width=998><img src="img/clear.gif" width=1 height=1"></td></tr>
    </table>
    <!-- END HEADER -->
</td></tr>	

</table>
<!-- END CENTERING HEADER -->	
</body>
</html>
