				<? include "template/column_spacer.inc"; ?>
                </tr>
                <tr><td colspan=6 height=5><img src="img/clear.gif" width=1 height=5></td></tr>
                <!-- PHILANTHROPY BANNER-->
                <tr><td colspan=6 align=center><a href="philanthropy.php"><img src="img/hvh_phil.gif" border=0></a></td></tr>
                </table>

            </td></tr>

            <!-- MOUNTAINS BANNER -->
            <tr><Td colspan=6><img src="img/mountains.gif" border=0 width=998 height=147></td></tr>
            </table>
                    
        </td>
        <td bgcolor=black width=1><img src="img/clear.gif" width=1 height=1"></td>
    </tr>       
    <tr><td bgcolor=black colspan=3 width=998><img src="img/clear.gif" width=1 height=1"></td></tr>
    </table>
    <!-- END HEADER -->
</td></tr>	

</table>
<!-- END CENTERING HEADER -->	
</body>
</html>
