<?php // include "util/connect.inc"; ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN">
<html>
<head>
<title><?php echo "$page_title" ?></title>
<link rel=stylesheet type="text/css" href="css/main.css">
<?php
//include "maps/North_America_head.inc";
//include "maps/Caribbean_head.inc";
//include "maps/Alaska_head.inc";
//include "maps/Europe_head.inc";
include "maps/Hawaii_head.inc";
?>
</head>
<body rightmargin='0' leftmargin='0' topmargin='0' bottommargin='0' marginheight='0' marginwidth='0'>
<!-- START CENTERING TABLE -->
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td align=center valign=top>
    <!-- START HEADER -->
    <table border=0 cellpadding=0 cellspacing=0 width=1000>
    <tr><td colspan=3 width=998><img src="img/clear.gif" width=1 height=20"></td></tr>
    <tr><td bgcolor=black colspan=3 width=998><img src="img/clear.gif" width=1 height=1"></td></tr>
    <tr>
        <td bgcolor=black width=1><img src="img/clear.gif" width=1 height=1"></td>
        <td width=998 bgcolor=white>
            <!-- BEGIN TOP NAV -->
            <table border=0 cellpadding=0 cellspacing=0 width=998>
            <Tr>
		<td><a href="index.php"><img src="img/home_off.gif" border=0></a></td>
                <td><a href="contact_us.php"><img src="img/contact_us_off.gif" border=0></a></td>
		<td><a href="about_us.php"><img src="img/about_us_off.gif" border=0></a></td>	
                <td><a href="book_a_place.php"><img src="img/book_off.gif" border=0></a></td>
                <td><a href="love_life.php"><img src="img/love_life_off.gif" border=0></a></td>
                <td><a href="book_a_place.php"><img src="img/nav_image.gif" border=0></a></td>
                <td><a href="solutions.php"><img src="img/solutions_top_off.gif" border=0></a></td>
            </tr>
            <tr><Td colspan=7><a href="index.php"><img src="img/hvh_top_logo.gif" border=0 width=998 height=175></a></td></tr>
            <tr><Td colspan=7><img src="img/clear.gif" border=0 width=1 height=20></td></tr>
			<tr><Td colspan=7>
                <table border=0 cellpadding=0 cellspacing=0 width="100%">
                <tr>

				<?php include "template/column_spacer.inc"; ?>		
