
<!-- BEGIN MAP -->
<table border=0 cellpadding=0 cellspacing=0>
<tr><td>
<?php
echo "<span class=map_header>North America</span>\n";
echo "<table border=0 cellpadding=0 cellspacing=0 width=\"100%\">";
echo "<tr><td bgcolor=\"#888888\" colspan=3><img src=\"img/clear.gif\" width=1 height=1></td></tr>";
echo "<tr><td width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td>";
echo "<td valign=top>";
include "maps/North_America_map_div.inc";
include "maps/North_America_map_script.inc";
echo "</td>";
echo "<td width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td>";
echo "</tr>";
echo "<tr><td colspan=3 width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td></tr>";
echo "</table>";
echo "<br />";



echo "<span class=map_header>Hawaii</span>\n";
echo "<table border=0 cellpadding=0 cellspacing=0 width=\"100%\">";
echo "<tr><td bgcolor=\"#888888\" colspan=3><img src=\"img/clear.gif\" width=1 height=1></td></tr>";
echo "<tr><td width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td>";
echo "<td valign=top>";
include "maps/Hawaii_map_div.inc";
include "maps/Hawaii_map_script.inc";
echo "</td>";
echo "<td width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td>";
echo "</tr>";
echo "<tr><td colspan=3 width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td></tr>";
echo "</table>";
echo "<br />";


echo "<span class=map_header>Caribbean</span>\n";
echo "<table border=0 cellpadding=0 cellspacing=0 width=\"100%\">";
echo "<tr><td bgcolor=\"#888888\" colspan=3><img src=\"img/clear.gif\" width=1 height=1></td></tr>";
echo "<tr><td width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td>";
echo "<td valign=top>";
include "maps/Caribbean_map_div.inc";
include "maps/Caribbean_map_script.inc";
echo "</td>";
echo "<td width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td>";
echo "</tr>";
echo "<tr><td colspan=3 width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td></tr>";
echo "</table>";
echo "<br />";






echo "<span class=map_header>Alaska</span>\n";
echo "<table border=0 cellpadding=0 cellspacing=0 width=\"100%\">";
echo "<tr><td bgcolor=\"#888888\" colspan=3><img src=\"img/clear.gif\" width=1 height=1></td></tr>";
echo "<tr><td width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td>";
echo "<td valign=top>";

include "maps/Alaska_map_div.inc";

include "maps/Alaska_map_script.inc";

echo "</td>";
echo "<td width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td>";
echo "</tr>";
echo "<tr><td colspan=3 width=1 bgcolor=\"#888888\"><img src=\"img/clear.gif\" width=1 height=1></td></tr>";
echo "</table>";
echo "<br />";




//echo "Europe\n";
//include "maps/Europe_map_div.inc";
//include "maps/Europe_map_script.inc";

?>
</td></tr>
<!--<tr><td><img src="img/us_map.gif" border=0 width=398 height=270></td></tr>-->
<!--<tr><td><img src="img/clear.gif" height=2 width=1></td></tr>-->
<!--<tr><td><img src="img/other_maps.gif" border=0></td></tr>-->
</table>
<!-- END MAP -->
