
<!-- BEGIN MAP -->
<table border=0 cellpadding=0 cellspacing=0>
<tr><td>
<?php
//echo "North America\n";
include "maps/North_America_map_div.inc";
include "maps/North_America_map_script.inc";

//echo "Hawaii\n";
include "maps/Hawaii_map_div.inc";
include "maps/Hawaii_map_script.inc";

//echo "Caribbean\n";
include "maps/Caribbean_map_div.inc";
include "maps/Caribbean_map_script.inc";

//echo "Alaska\n";
include "maps/Alaska_map_div.inc";
include "maps/Alaska_map_script.inc";

//echo "Europe\n";
//include "maps/Europe_map_div.inc";
//include "maps/Europe_map_script.inc";

?>
</td></tr>
<!--<tr><td><img src="img/us_map.gif" border=0 width=398 height=270></td></tr>-->
<!--<tr><td><img src="img/clear.gif" height=2 width=1></td></tr>-->
<!--<tr><td><img src="img/other_maps.gif" border=0></td></tr>-->
</table>
<!-- END MAP -->
