<!-- BEGIN SOLUTIONS -->
<table border=0 cellpadding=0 cellspacing=0>
<tr><Td><a href="solutions.php"><img src="img/owners_box_top.gif" border=0></a></td></tr>
<tr><td>
    <table border0 cellpadding=0 cellspacing=0 width="100%">
    <tr><td width=1 bgcolor="#ff3300"><img src="img/clear.gif" width=1 height=1></td>
		<Td>
            <table border=0 cellspacing=0 cellpadding=12 width="100%">
            <tr><Td align=center valig=top><a href="solutions.php"><img src="img/list_a_property.gif" border=0></a>
		<a href="solutions_second_home_owner.php"><img src="img/sol_but_one.gif" border=0 hspace=10></a>
            <a href="solutions_property_manager.php"><img src="img/sol_but_two.gif" border=0></a>
            <a href="solutions_hotels_inns.php"><img src="img/sol_but_three.gif" border=0 hspace=10></a></td></tr>
            </table>
		</td>
        <td width=1 bgcolor="#ff3300"><img src="img/clear.gif" width=1 height=1></td>
	</tr>
    <tr><Td colspan=3 bgcolor="#ff3300"><img src="img/clear.gif" width=1 height=1></td></tr>
    </table>
</td></tr>
</table>
<!-- END SOLUTIONS -->
