<!-- BEGIN SEARCH -->
<table border=0 cellpadding=0 cellspacing=0>
<tr><Td><img src="img/search_props_box.gif"></td></tr>
<tr><td valign=top>
    <table border0 cellpadding=0 cellspacing=0 width="100%">
    <tr><td width=1 bgcolor="#99cc99"><img src="img/clear.gif" width=1 height=1></td>
        <Td bgcolor="#e8f2ea" valign=top>
			<table border=0 cellpadding=0 cellspacing=0 width="100%">
			<tr><td width=20><img src="img/clear.gif" width=20 height=1></td>
			<td valign=top>
	        <table border=0 cellspacing=0 cellpadding=4 width="100%">
	        <tr><Td><span class=solutions_box>
				<form method=post name=search>
				<select name=location class=search_select>
				<option value="">By Location</option>
				</select>
				<br/>
				<select name=region class=search_select>
				<option value="">By Region</option>
				</select>
				<br/>
				<br/>
				<input type=submit name=search value='Search Properties'>

				</span>
				</form>
			</td></tr>
	        </table>
			</td>
			</tr>
			</table>
        </td>
        <td width=1 bgcolor="#99cc99"><img src="img/clear.gif" width=1 height=1></td>
    </tr>
    <tr><Td colspan=3 bgcolor="#99cc99"><img src="img/clear.gif" width=1 height=1></td></tr>
    </table>
</td></tr>
</table>
<!-- END SEARCH -->
