							<table border0 cellpadding=0 cellspacing=0 width="100%">
							<tr><td colspan=3 bgcolor=white><img src="img/clear.gif" width=1 height=16></td></tr>
							<tr><Td colspan=3 bgcolor="#eeeeee"><img src="img/clear.gif" width=1 height=1></td></tr>
							<tr><td width=1 bgcolor="#eeeeee"><img src="img/clear.gif" width=1 height=152></td>
								<Td valign=top bgcolor=#eeeeee>
									<table border=0 cellspacing=0 cellpadding=20 width="100%">
									<tr><Td><span class=testimonial>Marketing Tag Lines ???</span></td></tr>
									</table>
								</td>
								<td width=1 bgcolor="#eeeeee"><img src="img/clear.gif" width=1 height=1></td>
							</tr>
							<tr><Td colspan=3 bgcolor="#eeeeee"><img src="img/clear.gif" width=1 height=1></td></tr>
							</table>
