<!-- BEGIN TESTIMONIALS -->
<table border=0 cellpadding=0 cellspacing=0>
<tr><Td><img src="img/testimonials_top.gif"></td></tr>
<tr><td>
    <table border0 cellpadding=0 cellspacing=0 width="100%">
    <tr><td width=1 bgcolor="#dee8f2"><img src="img/clear.gif" width=1 height=1></td>
        <Td>
        <table border=0 cellspacing=0 cellpadding=20 width="100%">
        <tr><Td><span class=testimonial>"We went from $0 - $35,000 in bookings in 9 months!"</span>
            <br><span class=testimonial_tag>Erik Schultz - Executive Director, Arthur B Schultz Foundation, Sun Valley, ID</span>

            <Br><br><span class=testimonial>"The world needs more vacation."</span>
            <br><span class=testimonial_tag>Mike Testa - President & CEO, HVH</span>

            <Br><br><span class=testimonial>"On Demand or Cloud Computing is the future of the Software Industry."</span>
            <br><span class=testimonial_tag>Marc Benioff, Chairman & CEO <a href="www.salesforce.com" target=_blank>salesforce.com</a> (NYSE:CRM)</span>

         </td></tr>
         </table>
	     </td>
         <td width=1 bgcolor="#dee8f2"><img src="img/clear.gif" width=1 height=1></td>
	</tr>
    <tr><Td colspan=3 bgcolor="#dee8f2"><img src="img/clear.gif" width=1 height=1></td></tr>
    </table>
</td></tr>
</table>
<!-- END TESTIMONIALS -->
