

<table border=0 cellpadding=0 cellspacing=0 width=200>

<tr><Td><img src="img/corner_tl.gif"></td>
	<td valign=top>
		<table border=0 cellpadding=0 cellspacing=0 width="100%">
		<tr><Td bgcolor="#999999"><img src="img/clear.gif"></td></tr>
		</table>
	</td>
	<td><img src="img/corner_tr.gif"></td>
</tr>
<tr>
	<td>
		<table border=0 cellpadding=0 cellspacing=0>
		<tr><Td bgcolor="#999999"><img src="img/clear.gif" width=1 height=126></td></tr>
		</table>
	</td>
	<td valign=top class=entry_desc align=center>

		<a href="solutions_godaddy.php"><img src="img/chart_godaddy.gif" vspace=10 hspace=10 border=0></a>
		<br>Domains, Wesites, Email
	</td>
	<td align=right>
		<table border=0 cellpadding=0 cellspacing=0>
		<tr><Td bgcolor="#999999"><img src="img/clear.gif" width=1 height=126></td></tr>
		</table>
	</td>
</tr>
<tr><Td><img src="img/corner_bl.gif"></td>
	<td valign=bottom>
		<table border=0 cellpadding=0 cellspacing=0 width="100%">
		<tr><Td bgcolor="#999999"><img src="img/clear.gif"></td></tr>
		</table>
	</td>
	<td><img src="img/corner_br.gif"></td>
</tr>
</table>

