<!-- BEGIN CONTACT INFO - NOTHING ABOVE THIS LINE-->
<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top class=reg_copy>
<h2>Contact Us</h2>
Please call or email us anytime.&nbsp; We are committed to responding to you immediately and we look forward to speaking with you.
<br><Br>
Thomas Beebe<br />888-858-6562<br /><a href="mailto:thomas@hvh.com">thomas@HVH.com</a><br /><br>

If you are on the east coast, please consider that Hawaiian Standard Time is 5-6 hours behind you depending on daylight savings
<br><br>
</td></tr>
</table>
<!-- END CONTACT INFO - NOTHING BELOW THIS LINE -->
