<?php   $prop_cat = 'Signature Homes';
        $cat = 'signature_home';
        $count_it = 1;
?>
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><Td valign=top>
<table border=0 cellpadding=30 cellspacing=0 width="100%">
<tr><Td class=reg_copy>
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td class=reg_copy>
<h2>Welcome to HVH!</h2>

Your single-site resource for comprehensive services across the entire vacation rental industry.  Our mission is to connect <b>travelers</b> with <B>property owners</b> and to provide both with unique services that truly foster a '<B>vacation community</b>'. 
<br><Br>
<b>TRAVELERS</b><br>
Looking for the perfect vacation rental?  <B>SEARCH</b> our extensive list of qualified vacation rental properties to find that special spot for you and your family. 
<br><Br>
<b>OWNERS AND MANAGERS</b><br>
Ready to maximize bookings, maintain satisfied return customers, and streamline your entire rental operation?  <a href="contact_us.php"><b><u><font color="black">LIST your property on hvh.com</font></u></b></a>, then check out <a href="solutions.php"><b><u><font color=black>HVH MANAGEMENT SOLUTIONS</font></u></b></a> and become part of an industry revolution.  Nothing is simpler, more effective or more affordable at any level.




</td>
</tr>
</table>

</td></tr>
</table>
</td>
<td width=1 bgcolor="#496b97"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#d2eefe" width=165 align=center>


<?php include "elements/owners_nav.inc"; ?>
</td>
</tr>
</table>
