<?php   $prop_cat = 'Signature Homes';
        $cat = 'signature_home';
        $count_it = 1;
?>
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><Td valign=top>
<table border=0 cellpadding=30 cellspacing=0 width="100%">
<tr><Td class=reg_copy>
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td class=reg_copy>
<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><h2>Welcome to HVH!</h2></td>
	</tr>
</table>
<object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/OinzbVl3z3s&hl=en&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/OinzbVl3z3s&hl=en&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>

<br><Br>
Your single-site resource for comprehensive services across the entire vacation rental industry.  Our mission is to connect <b>travelers</b> with <B>property owners</b> and to provide both with unique services that truly foster a '<B>vacation community</b>'. 



</td>
</tr>
</table>

</td></tr>
</table>
</td>
<td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#ffffff" width=215 align=center>


<?php include "elements/owners_nav.inc"; ?>
</td>
</tr>
</table>
