<!-- BEGIN LOVE LIFE CONTENT - NOTHING ABOVE THIS LINE-->
<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>
<h2>Love Life</h2>
<p>Hideaway Vacation Homes strives to offer a variety of high end vacation
rental homes in beautiful destination locations around the globe. Our
properties offer <strong>peaceful privacy, rich appointments and inspiring locations.</strong></p>

<p>As our world increases in complexity and demands we feel it is very
important for us all to take time away and slow down our pace of life
if only for a few days. We have made it our business to provide places for you to experience blissful relaxation. </p>

<p>If you have a home that fits this description
and are interested in adding it to our listing please let us know. </p>

<p><a href="contact_us.php">Learn more about our matching contribution program.</a> </p><br><Br>						

<!-- END LOVE LIFE CONTENT -- NOTHING BELOW THIS LINE-->
</td>
</tr>
</table>
