<!-- BEGIN PHILANTHROPY CONTENT - NOTHING ABOVE THIS LINE-->
<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>
<h2>Philanthropy</h2>
<P>To honor our gratitude and respect for these beautiful destinations where we
offer vacation accommodations we have established philanthropy matching
projects in these areas. Guests are given the option to donate a
percentage of their rental expense to charitable organizations active
in local communities where they will be vacationing.</p>

<P>HVH is also partnered with the Arthur B. Schultz foundation <a href="http://www.absfoundation.org/programs.html">www.ABSfoundation.org</a>.</p>

<p>Please contact <a href="http://www.hvh.com/properties/contact.html">Thomas Beebe</a> to learn more about our philanthropy and matching contribution programs.</p>

<p>Links:</p>

<li><a href="http://www.absfoundation.org" class=download_link target=_blank>ABS Foundation - www.absfoundation.org</a>
<li><a href="http://www.salesforcefoundation.org" class=download_link target=_blank>Salesforce Foundation - www.salesforcefoundation.org</a>
<li><a href="http://www.confluencefund.org" class=download_link target=_blank>Confluence Fund  www.confluencefund.org</a>
<li><a href="http://www.kiva.org" class=download_link target=_blank>Micro-Lending www.kiva.org</a>
<li><a href="http://www.google.org" class=download_link target=_blank>Google - google.org</a>
<li><a href="https://vpos.skipjack.com/ps/absfoundation/donate.aspx" class=download_link target=_blank>Donate a wheelchair to a disabled person in Vietnam</a> 

<br><Br>

<table cellpadding=6 cellspacing=8 width="100%" >
<Tr>
<Td valign=middle align=center width=1 class=dot><a href="http://www.absfoundation.org" class=download_link target=_blank><img src="img/abs_logo.gif" border=0></a><br>
</td>
<Td valign=middle align=center class=dot><a href="http://www.confluencefund.org" class=download_link target=_blank><img src="img/phil_conf_fund.gif" border=0></a><br>
</td>

<Td valign=middle align=center width=1 class=dot>
<a href="https://vpos.skipjack.com/ps/absfoundation/donate.aspx" class=download_link target=_blank><img src="img/phil_rough_rider.gif" border=0 width=100 height=101></a>
</td>
</tr>
<tr>
<Td valign=middle align=center width=1 class=dot><a href="http://www.kiva.org" class=download_link target=_blank><img src="img/phil_kiva.gif" border=0></a><br>
</td>


<Td valign=middle align=center class=dot><a href="http://www.salesforcefoundation.org" class=download_link target=_blank><img src="img/phil_sff.gif" border=0></a></td>
<td valign=middle align=center width=1 class=dot><a href="http://www.google.org" class=download_link target=_blank><img src="img/phil_google_org.gif" border=0></a></td>


</tr>
</table>

<!-- END PHILANTHROPY  CONTENT -- NOTHING BELOW THIS LINE-->
</td>
</tr>
</table>
