<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td align=center valign=top>

<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top class=reg_copy width="66%">
<h2>Quickbooks Online</h2>

Web-based version of their industry standard financial accounting package for small businesses:

<ul>
<li>General Ledger
<li>Accounts Receivable
<li>Accounts Payable
<li>Expense Management
<li>Revenue Accounting
<li>Payroll
<li>Tax Accounting
</ul>
<br>
Save money on Bookkeepers and Accountants by automatically translating a booking into the language of Quickbooks.

</td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td valign=top align=right>

<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/chart_intuit.gif"></td></tr>
</table>

</td>
</tr>
</table>

</td></tr>
</table>


</td>

<td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#ffffff" width=215 align=center>


<?php include "elements/owners_nav.inc"; ?>
</td>

</td></tr>
</table>


<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
