<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td align=center valign=top>

<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top class=reg_copy width="66%">
<h2>Google Apps</h2>
HVH harnesses the power of Google.
<ul>
<li>Search Optimization
<li>Google Calendar
<li>Browser Toolbar
<li>Google Maps
<li>Google Apps
</ul>
<br>
Get More for you internet marketing!


</td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td valign=top align=right>

<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/chart_google.gif"></td></tr>
</table>

</td>
</tr>
</table>

</td></tr>
</table>


</td>

<td width=1 bgcolor="#496b97"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#d2eefe" width=165 align=center>


<?php include "elements/owners_nav.inc"; ?>
</td>

</td></tr>
</table>


<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
