<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td align=center valign=top>

<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top class=reg_copy width="66%">
<h2>godaddy.com Internet Services</h2>
Go Daddy is the world’s largest and most comprehensive domain name registrar.

<ul>
<li>Website Builder
<li>Web Hosting
<li>Domain Name Services
<li>Email Accounts
</ul>



</td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td valign=top align=right>

<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/chart_godaddy.gif"></td></tr>
</table>

</td>
</tr>
</table>

</td></tr>
</table>


</td>

<td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#ffffff" width=215 align=center>

<?php include "elements/owners_nav.inc"; ?>
</td>

</td></tr>
</table>


<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
