<td class=content valign=top>
<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td align=center valign=top>

<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top width="68%" class=reg_copy>
<h2>Second Home Owner</h2>
<p>HVH Solutions 2nd Home Edition provides everything a homeowner needs to run a rental business.<br/><br/>
We deliver an end-to-end business solution including the following capabilities: 
<ul>
<li>Website/email Management
<li>Sales & Marketing
<li>Contact Management
<li>Online Booking
<li>Availability Calendar
<li>Contracts and Rental Agreements
<li>Maintenance Tracking
<li>Free listing on <a href="index.html">HVH.com</a>
</ul>
Pricing - Annual subscription of $195/yr for a single user with one property. <!--Additional users and properties are available and described in US Price List (Button: download here to the Price List) Button (purchase here) (link to credit card acceptance form) Button (download the product spec sheet) Take a test drive (www.appexchange.com)--></p><br><Br>
</td>

<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td valign=top align=right width="40%">

<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/sol_but_one.gif"></td></tr>
</table>
<br>

<a href="contact_us.php" class=download_link>Download the Product Spec Sheet<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="contact_us.php" class=download_link>Download the Company Overview<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="contact_us.php" class=download_link>See a demo of the 2nd Home Edition<img src="img/pdf_ico_small.gif" hspace=6 border=0></a></br>

</td>
</tr>
</table>

</td></tr>
</table>


</td>

<td width=1 bgcolor="#496b97"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#d2eefe" width=165 align=center>


<?php include "elements/owners_nav.inc"; ?>
</td>

</td></tr>
</table>



<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
</td>
