<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td align=center valign=top>

<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top class=reg_copy width="66%">
<h2>Paypal</h2>
Using Paypal'site Payments Pro, HVH offers online bookings that are quick, easy, and secure.
<ul>

<li>Immediate Confirmation
<li>Recurring Payments
<li>Transaction Approvals
<li>All Major Credit Cards
<li>Highest Security
<li>200M User Accounts
</ul>
<br>
Using the most sophisticated Internet Payment solution in the industry, HVH delivers and secure and reliable transaction.  


</td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td valign=top align=right>

<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/chart_paypal.gif"></td></tr>
</table>

</td>
</tr>
</table>

</td></tr>
</table>


</td>

<td width=1 bgcolor="#496b97"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#d2eefe" width=165 align=center>


<?php include "elements/owners_nav.inc"; ?>
</td>

</td></tr>
</table>


<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
