<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top class=reg_copy>
<h2>Property Manager</h2>
HVH provides everything a property manager needs to increase bookings and reduce expenses. We deliver and end-to-end, web based solution that manages the entire process from lead generation to recognized revenue.

<ul>
<li>Website/email Management <br>
<li>Sales & Marketing <br>
<li>Contact Management <br>
<li>Online Bookings & Reservations <br>
<li>Customer Database <br>
<li>Availability Calendar <br>
<li>Contracts and Rental Agreements <br>
<li>Maintenance Tracking <br>
<li>Fees and Commissions<Br>
<li>Financial Accounting<br>
<li>Occupancy Rate Reporting<br>
<li>Business Process Outsourcing<Br>
<li>Free listing on <a href="index.php">HVH.com</a>
</ul>

Pricing

<ul>
<li>Annual Subscription of $885/yr includes 3 users and up to 50 properties.
<li>Integrated Financial Accounting Option is an addtional $995/yr.
<li>Additional properties and users are available to for an additional fee. 
<!--Click here to become a partner: (Button for HVH.com/Partners) Purchase (Button to take someones credit card/paypal etc.) Product Spec Sheet (Button) Test Drive (www.appexchange.com) Usual Links along the bottom (hvh.com, contact us, love life, HVH Solutions)--></p><br><Br>
</ul>


</td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td valign=top align=right width="40%">

<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/sol_but_two.gif"></td></tr>
</table>
<br>
<a href="" class=download_link>Download the Product Spec Sheet<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="" class=download_link>Download the Company Overview<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="" class=download_link>See a demo of the 2nd Home Edition<img src="img/pdf_ico_small.gif" hspace=6 border=0></a></br>

</td>
</tr>
</table>

</td></tr>
</table>

<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
