<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->


<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>


<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top width="60%" class=reg_copy>
<h2>Hotels, Inns, and B<font face=arial size=3>&</font>B's</h2>
Whether you have a few rooms in a quaint Bed & Breakfast or a hundred rooms in a posh hotel, HVH Solutions offers end-to-end business applications that provide complete visibility into your business through real-time reporting and dashboards. Our web-based system delivers process efficiencies, higher revenues, and lower costs for much less than what you're paying today. <!--To download a total cost of ownership model, click here (webform).--> 
<br><Br>HVH has taken the ease of use of consumer sites like ebay, Amazon, Google, and Yahoo and created a business solution for the Vacation Rental Management Industry available through the browser. Our application is easy to use and intuitive to learn, yet comprehensive enough to run a large hotel. The solution offers everything a hotelier needs to track property maintenance, reservations, revenues, and expenses. Our system increases sales, improves internet reservation capture, automates bookings, and provides a permanent customer database. <!--(Download detailed Product Spec Sheet Button)--> 
<br><Br>The HVH Hotel and B&B Edition also includes a complete list of functional capabilities:






<ul>
<li>Website/email Management
<li>Sales & Marketing 
<li>Contact Management
<li>Online Bookings & Reservations
<li>Customer Database
<li>Availability Calendar
<li>Contracts and Rental Agreements
<li>Maintenance Tracking 
<li>Fees and Commissions
<li>Financial Accounting
<li>Occupancy Rate Reporting
<li>Business Process Outsourcing
<li>Free listing on <a href="index.php">HVH.com!</a>
</ul>

Annual Subscription of $595/yr. includes 3 users and unlimited rooms. Integrated Financial Accounting Option is an addtional $595/yr. Additional properties and users are available. <!--To download the US Price List, please click here (back to the webform). Purchase Here (Button to take someones credit card/paypal etc.) Download detailed Product Spec Sheet (Button) Take a Test Drive (www.appexchange.com) Usual Links along the bottom (hvh.com, contact us, love life, HVH Solutions)-->
<br><Br>


</td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>


<td valign=top align=right width="40%">
<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/sol_but_three.gif"></td></tr>
</table>
<br>

<a href="contact_us.php" class=download_link>Download the Product Spec Sheet<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="contact_us.php" class=download_link>Download the Company Overview<img src="img/pdf_ico_small.gif" hspace=6 border=0></a><br/>
<a href="contact_us.php" class=download_link>See a demo of the 2nd Home Edition<img src="img/pdf_ico_small.gif" hspace=6 border=0></a></br>

</td>
</tr>
</table>

</td></tr>
</table>

<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
