<! -- BEGIN SOLUTIONS CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top align=center>

<table border=0 cellpadding=20 cellspacing=0 width="100%">
<tr><Td valign=top align=center>

<h3>HVH offers Integrated Web Technologies</h3>

<table border=0 cellpadding=2 cellspacing=0>
<tr><Td><?php include "content/chart_google.inc"; ?></td>
	<Td><img src="img/arrow_side.gif"></td>
	<td><?php include "content/chart_hvh.inc"; ?></td>
	<td><img src="img/arrow_side.gif"></td>
	<td><?php include "content/chart_intuit.inc"; ?></td>
</tr>
<tr><td></td>
	<td><img src="img/arrow_left.gif"></td>
	<td align=center><img src="img/arrow_up.gif"></td>
	<td><img src="img/arrow_right.gif"></td>
	<td></td>
</tr>
<tr><Td><?php include "content/chart_godaddy.inc"; ?></td>
	<Td valign=top></td>
	<td align=center><?php include "content/chart_force.inc"; ?></td>
	<td></td>
	<td><?php include "content/chart_paypal.inc"; ?></td>
</tr>


</table>




</td></tr>
</table>
<Br><Br><Br><Br>
<Br><Br><Br><Br>
<Br><Br><Br><Br>
</td>
<td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#ffffff" width=165 align=center>


<?php include "elements/owners_nav.inc"; ?>
</td>

</td></tr>
</table>
<! -- END SOLUTIONS CONTENT - NOTHING BELOW THIS LINE -->
