<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td align=center valign=top>

<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top class=reg_copy width="66%">
<h2>force.com Platform</h2>
Salesforce is the world's leading Customer Relationship Management (CRM) provider and the engine behind HVH.
<ul>
<li>Contacts
<li>Properties
<li>Inquiries
<li>Bookings
<li>Rental Agreements
<li>Property Management
<li>Email Marketing
</ul>

The Force.com Platform enables us to build unique applications for the travel industry.

<br><br>
HVH is a native Force.com App leveraging:<Br>

<ul>
<li>APEX Code
<li>Triggers
<li>Workflow
<li>Advanced Formula Fields
<li>Custom Objects, Fields, and Buttons
<li>S-Force Toolkit
<li>PHP 5 SOAP Extension Toolkit 
<li>AppExchange API 7.0
<li>Coming Soon:  Visualforce

</ul>


</td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td valign=top align=right>

<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/chart_force.gif"></td></tr>
</table>

</td>
</tr>
</table>

</td></tr>
</table>


</td>

<td width=1 bgcolor="#cccccc"><img src="img/clear.gif" width=1 height=1></td>
<td valign=top bgcolor="#ffffff" width=215 align=center>

<?php include "elements/owners_nav.inc"; ?>
</td>

</td></tr>
</table>


<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
