<table border=0 cellpadding=30 cellspacing=0 width="100%">
<tr><Td class=reg_copy>
<table border=0 cellpadding=0 cellspacing=0 width="100%">
<Tr><Td colspan=2 class=reg_copy valign=top>
<h2>Customer Success</h2>
Hi Mike,
<br><Br>
Congratulations on a successful implementation in 2008!  I wanted to update you that using the system we've booked orders for 315 wheelchairs since we launched the program last year!!
<br><Br>
From the beginning you provided the vision and execution of the technology solution.  You built a comprehensive system with an extremely small, non-profit budget.  During the weekly project management meetings, you showed dogged determination to meet project deadlines and stay under budget.  
<br><Br>
Since going live, donors are constantly praising the personal nature of the system.  By connecting donors with the people receiving the wheelchairs, we show people exactly where their money is going.  The system really makes our donors feel good about giving money to our programs.
</td></tr>
<tr><td valign=top class=reg_copy>
<br>Thanks so much for making it happen,
 <br><Br>
Erik Schultz<br>
Executive Director<br>
Arthur B. Schultz Foundation<br>
Ketchum, ID 83340 USA
</td>
<td valign=bottom align=right>
<img src="img/abs_logo.gif" border=0 vspace=8>
</td>
</tr>
</table>

<hr noshade size=1 color="#cccccc">



<table border=0 cellpadding=0 cellspacing=0 width="100%">
<Tr><Td colspan=2 class=reg_copy valign=top>
During the three years we worked together at Oracle, you were an  integral member of our Global Account Management team.  You were loyal, persistent, hard working, and dedicated to  achieving our goals.  In additional, you had the ability to manage and facilitate complex sales cycles, such as Applied Materials, Sun Microsystems, Apple and AMD.   With your help we  were able to bring in approximately $100M in software  license revenue, but also the drag along revenue such as consulting and educational services.    These efforts directly resulted in being recognized as the number one sales team worldwide for three consecutive years ('97-'99) at the Oracle President's Club.
<br><Br>
I  am sure you will continue your track record of success in your new endeavors.
</td></tr>
<tr><Td valign=top class=reg_copy><br>
Good Luck,<br><Br>

Elizabeth Baker<br>
SVP, SAP Strategic Initiatives
</td>
<td align=right valign=bottom>
<img src="img/sap_logo.gif" border=0>
</td>
</tr>
</table>
<hr noshade size=1 color="#cccccc">





<table border=0 cellpadding=0 cellspacing=0 width="100%">
<Tr><Td colspan=2 class=reg_copy valign=top>
Mike, 
<br><Br>

Having worked countless deals with you over a 10 year span at Oracle and Corio, I would tell your prospects and investors about your strong business acumen, history of winning, and ability to influence decisions to reach the right solution for the customer and achieve business objectives. 
<br><Br>
One of my fondest memories of our work together was when we closed largest deal in Corio's history to date - $10M over 3 years with Quadrem, the mining consortium of 3M, DeBeers, and Alcoa. Their rigorous RFP and negotiation process was one of the toughest I've come across. That deal never would have happened without your leadership. Your work to help architect the right technology solution, steering committee leadership and continuous involvement in the project management office ensured that objectives were met and a smooth implementation. 

</td></tr>
<tr><Td valign=top class=reg_copy><br>

Michael Butler<br>
Director, Operations<br>
HP Home & Home Office
</td>
<td align=right valign=bottom>
<img src="img/hp_logo.gif" border=0 vspace=4>
</td>
</tr>
</table>
<hr noshade size=1 color="#cccccc">





<table border=0 cellpadding=0 cellspacing=0 width="100%">
<Tr><Td colspan=2 class=reg_copy valign=top>
I've known Mike since 2006 and Mike's leadership and guidance were instrumental in helping us select the right technology for our business and leverage the solution's best practices. Under Mike's watch we were successful in deploying over 200 users of Salesforce Service & Support across multiple groups globally within HP's Home and Home Office division. During the entire engagement Mike was extremely reliable and he took the time to understand our needs and deliver results throughout the relationship of our two compnes.

The business results of our engagement with Salesforce.com has been a reduction in call handling times, an improvement in problem resolution handling, a more efficient escalation process and improved Total Customer Satisfaction.  Also, as an Ops Director, I'm able to utilize the reports and dashboards to actively manage my business in real time. 
</td></tr>
<tr><Td valign=top class=reg_copy><br>

Best,
<br><br>
Craig Whetstone <br>
Engagement Support Executive <br>
IBM Corporation | Applications on Demand<br>

</td>
<td align=right valign=bottom>
<img src="img/ibm_logo.gif" border=0 vspace=4>
</td>
</tr>
</table>
<hr noshade size=1 color="#cccccc">


<table border=0 cellpadding=0 cellspacing=0 width="100%">
<Tr><Td colspan=2 class=reg_copy valign=top>
Mike,
<br><Br>
I just wanted to send a quick note to let you know how much I appreciate all your hard work at National Semiconductor.  When we first met, National had no relationship with Salesforce.com whatsoever.  However, within one year of our first meeting, we had implemented Contacts, Leads, Engineering Samples and DesignWin/Opportunity management for 500 users in 12 languages around the world!
<br><br>
Every time we needed something from Salesforce.com, you were there to help us.  We appreciate your experience and advice as you delivered the resources we needed to meet our goals and objectives. 
<br><Br>
Thanks for all your help.

</td></tr>
<tr><Td valign=top class=reg_copy><br>

Regards,<br><Br>
Raj Harapanahalli<br>
IT Director,<br>
Sales & Marketing Systems
</td>
<td align=right valign=bottom>
<img src="img/natl_logo.gif" border=0 vspace=4>
</td>
</tr>
</table>






</td></tr>
</table>
