<center><img src="img/hb_ad.gif" border=0><br>
<script language="JavaScript" type="text/javascript">
	AC_FL_RunContent(
		'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0',
		'width', '264',
		'height', '184',
		'src', 'hideaway',
		'quality', 'high',
		'pluginspage', 'http://www.adobe.com/go/getflashplayer',
		'align', 'middle',
		'play', 'true',
		'loop', 'true',
		'scale', 'showall',
		'wmode', 'window',
		'devicefont', 'false',
		'id', 'hideaway',
		'bgcolor', '#ffffff',
		'name', 'hideaway',
		'menu', 'true',
		'allowFullScreen', 'false',
		'allowScriptAccess','sameDomain',
		'movie', 'swf/hideaway',
		'salign', ''
		); //end AC code
</script>
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="264" height="184" id="hideaway" align="middle">
	<param name="allowScriptAccess" value="sameDomain" />
	<param name="allowFullScreen" value="false" />
	<param name="movie" value="swf/hideaway.swf" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" />	
	<embed src="swf/hideaway.swf" quality="high" bgcolor="#ffffff" width="264" height="184" name="hideaway" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" />
	</object>
</center>
