<! -- BEGIN SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING ABOVE THIS LINE -->

<table border=0 cellpadding=30 cellspacing=0 width="100%">
<Tr><td valign=top>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><td valign=top class=reg_copy>
<h2>List Your Property</h2>

<table border=0 cellpadding=0 cellspacing=0 width="100%">
<tr><Td class=reg_copy>
To List your property fill out the the form below and click submit. Mike we probably want some better text here explaining just how the process goes.<Br><Br>

<form name=list_prop_1 method=post action="list_your_property.php">




<? include "../phpdev/content/upload_contact_info.inc"; ?>



</td></tr>
</table>


</td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td width=1 bgcolor="#e2e2e1"><img src="img/clear.gif" width=1 height=1></td>
<td width=10><img src="img/clear.gif" width=10 height=1></td>

<td valign=top align=right width="40%">

<table border=0 cellpadding=0 width="100%">
<tr><Td align=center><img src="img/list_a_property.gif"></td></tr>
</table>
<br>

</td>
</tr>
</table>

</td></tr>
</table>

<! -- END SOLUTIONS 2ND HOME OWNER CONTENT - NOTHING BELOW THIS LINE -->
